# Base config for multiple namespaces

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../crds

resources:
  - namespace.yaml
  - istio-ingress.yaml
  - discovery.yaml

patchesStrategicMerge:
  - allocation.yaml

