apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: istio-sdsagent
  namespace: {{ .Release.Namespace }}
  labels:
    app: istio-sdsagent
    istio: sdsagent
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      istio: sdsagent
  template:
    metadata:
      labels:
        app: istio-sdsagent
        istio: sdsagent
        release: {{ .Release.Name }}
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: istio-sdsagent
{{- if .Values.global.priorityClassName }}
      priorityClassName: "{{ .Values.global.priorityClassName }}"
{{- end }}
      containers:
        - name: sdsagent
{{- if contains "/" .Values.sdsagent.image }}
          image: "{{ .Values.sdsagent.image }}"
{{- else }}
          image: "{{ .Values.global.hub }}/{{ .Values.sdsagent.image }}:{{ .Values.global.tag }}"
{{- end }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy | default "Always" }}
          args:
          {{- if .Values.global.logAsJson }}
            - --log_as_json
          {{- end }}
          {{- if .Values.logLevel }}
            - --log_output_level={{- if .Values.logLevel }}
          {{- end }}
          volumeMounts:
            - mountPath: /var/run/sds
              name: sdsudspath
          env:
            - name: CA_PROVIDER
              value: {{ .Values.sdsagent.caProvider }}
            - name: CA_ADDR
              value: {{ .Values.sdsagent.caAddr }}
          {{- if .Values.sdsagent.env }}
          {{- range $key, $val := .Values.sdsagent.env }}
            - name: {{ $key }}
              value: "{{ $val }}"
          {{- end }}
          {{- end }}
            - name: "Trust_Domain"
              value: "{{ .Values.global.trustDomain }}"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      volumes:
        - name: sdsudspath
          hostPath:
            path: /var/run/sds
      affinity:
      {{- include "nodeaffinity" . | indent 6 }}
      {{- include "podAntiAffinity" . | indent 6 }}
{{- if .Values.sdsagent.tolerations }}
      tolerations:
{{ toYaml .Values.sdsagent.tolerations | indent 6 }}
{{- end }}
  updateStrategy:
    type: RollingUpdate
