# Equivalent with istio1.2.x default config, using new installer.
# All components in istio-system, upgrade/downgrade possible.

# Requires kustomize/cluster to be installed first.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gen-istio-citadel.yaml
  - gen-istio-config.yaml
  - gen-istio-discovery.yaml
  - gen-istio-autoinject.yaml
  - gen-istio-ingress.yaml
  - gen-istio-prometheus.yaml
  - gen-istio-grafana.yaml

